DOMAIN-SUFFIX,v4.plex.tv
DOMAIN-SUFFIX,dler.cloud
DOMAIN-SUFFIX,dler.pro
DOMAIN-SUFFIX,oics.net
DOMAIN-SUFFIX,po0.com
DOMAIN-SUFFIX,humblebundle.com
DOMAIN-SUFFIX,lg.xtom.com
DOMAIN-KEYWORD,longemby
DOMAIN,www.uhdnow.com
DOMAIN,smart.uhdnow.com
DOMAIN,speed.uhdnow.com
DOMAIN-SUFFIX,uhdnow.online
IP-CIDR,45.89.235.98/32,no-resolve
IP-CIDR,82.40.34.207/32,no-resolve
IP-CIDR,64.186.229.140/32,no-resolve
IP-CIDR,45.131.71.84/32,no-resolve
