DOMAIN-SUFFIX,v4.plex.tv
DOMAIN-SUFFIX,dler.cloud
DOMAIN-SUFFIX,dler.pro
DOMAIN-SUFFIX,oics.net
DOMAIN-SUFFIX,humblebundle.com
IP-CIDR,103.112.1.61/32,no-resolve
IP-CIDR,82.40.34.207/32,no-resolve
IP-CIDR,23.249.19.121/32,no-resolve
IP-CIDR,64.186.229.140/32,no-resolve
IP-CIDR,45.131.71.84/32,no-resolve
IP-CIDR,45.147.48.147/32,no-resolve
# IP-CIDR,38.55.39.19/32,no-resolve
IP-CIDR,192.109.228.135/32,no-resolve
