DOMAIN-KEYWORD,tracker
DOMAIN-KEYWORD,torrent
DOMAIN-KEYWORD,aria2
DOMAIN-KEYWORD,thunder
DOMAIN-KEYWORD,xlliveud
DOMAIN-KEYWORD,xunlei
DOMAIN-KEYWORD,yunpan
DOMAIN-KEYWORD,announce
USER-AGENT,Thunder*
USER-AGENT,XLDownload*
USER-AGENT,Xunlei*
# DOMAIN-SUFFIX,download.nvidia.